### ISSUE TITLE
GET event/time/plan 응답 관련.

### ISSUE THREAD

**Issue by devyjh** [arckjh/api-redis#3]
응답 형식
- ["5","2018-09-13 00:00","2018-09-13 20:00","5","3"]
- key-value 형식이 아닌, 순서형으로 내려오고 있습니다.
- 우선, 항상 같은 순서로 나열된다는 가정하에 개발 진행 중입니다.

**Comment by arckjh** [comment]
버그이군요;;;
키-밸류 형식으로 출력하도록 코딩을 했다고 생각했는데~ 단위테스트에서도 200 응답만 테스트를 해서 미처 확인을 못했습니다. 해당 부분건 수정 후 알려드리도록 하겠습니다.

**Comment by arckjh** [comment]
버그 픽스
